### ISSUE TITLE
tkgui.py generates error

### ISSUE THREAD

**Issue by brktyln2** [mzahana/siyi_sdk#11]
Exception in thread Thread-1 (recvLoop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/bura7/Desktop/SAVX/Dron_buyuk/SDK/siyi_sdk-main/siyi_sdk.py", line 224, in recvLoop
    self.bufferCallback()
  File "/mnt/c/Users/bura7/Desktop/SAVX/Dron_buyuk/SDK/siyi_sdk-main/siyi_sdk.py", line 232, in bufferCallback
    buff,addr = self._socket.recvfrom(self._BUFF_SIZE)
TimeoutError: timed out
 [INFO] 2024-03-20 09:43:00,573 [SIYISDK::disconnect] : Stopping all threads
 [ERROR] 2024-03-20 09:43:00,574 [SIYISDK::connect] :   Failed to connect to camera
No connection
 [WARNING] 2024-03-20 09:43:00,904 [SIYISDK::connectionLoop] :  Connection checking loop is stopped. Check your connection!

I  get this error when I try to operate the gui by using the  python3 gui/tkgui.py command. Thanks in advance!

**Comment by mzahana** [comment]
Hi @brktyln2 

* The most common cause of a `TimeoutError` during a network operation is an issue with the network connection. This could be due to the camera or device being unreachable over the network, possibly because it's turned off, out of range, or not properly configured for network communication.
* If the IP address or port specified in the SDK's configuration doesn't match the camera's actual network interface settings, the SDK won't be able to establish a connection.
* Ensure that all devices are powered on and functioning correctly. Verify the camera is correctly set up for network communication.

**Comment by brktyln2** [comment]
Well the camera connection seems to fail and reappear while running the code. I'm using SIYI FPV to continuously monitor the recordings of the camera. The test codes seemed to work fine without affecting the connection but the gui code seems to hinder it. The physical connection (the ethernet connection) is rock solid though.

**Comment by brktyln2** [comment]
I found the source of the error. Apparently one of the scripts had a different IP adress and I had overlooked it. The connection was stabilised upon changing the IP Adress. Thanks alot for the help!
